# rankings_data.py
# Simplified player rankings for 2025 fantasy draft

RANKINGS = [
    {"rank": 1, "name": "Ja'Marr Chase", "team": "CIN", "position": "WR"},
    {"rank": 2, "name": "Bijan Robinson", "team": "ATL", "position": "RB"},
    {"rank": 3, "name": "Saquon Barkley", "team": "PHI", "position": "RB"},
    {"rank": 4, "name": "Justin Jefferson", "team": "MIN", "position": "WR"},
    {"rank": 5, "name": "Jahmyr Gibbs", "team": "DET", "position": "RB"},
    {"rank": 6, "name": "CeeDee Lamb", "team": "DAL", "position": "WR"},
    {"rank": 7, "name": "Puka Nacua", "team": "LAR", "position": "WR"},
    {"rank": 8, "name": "Amon-Ra St. Brown", "team": "DET", "position": "WR"},
    {"rank": 9, "name": "Malik Nabers", "team": "NYG", "position": "WR"},
    {"rank": 10, "name": "Brian Thomas Jr.", "team": "JAC", "position": "WR"},
    {"rank": 11, "name": "Derrick Henry", "team": "BAL", "position": "RB"},
    {"rank": 12, "name": "Nico Collins", "team": "HOU", "position": "WR"},
    {"rank": 13, "name": "Ashton Jeanty", "team": "LV", "position": "RB"},
    {"rank": 14, "name": "De'Von Achane", "team": "MIA", "position": "RB"},
    {"rank": 15, "name": "Brock Bowers", "team": "LV", "position": "TE"},
    {"rank": 16, "name": "A.J. Brown", "team": "PHI", "position": "WR"},
    {"rank": 17, "name": "Christian McCaffrey", "team": "SF", "position": "RB"},
    {"rank": 18, "name": "Drake London", "team": "ATL", "position": "WR"},
    {"rank": 19, "name": "Jonathan Taylor", "team": "IND", "position": "RB"},
    {"rank": 20, "name": "Josh Jacobs", "team": "GB", "position": "RB"},
    {"rank": 21, "name": "Bucky Irving", "team": "TB", "position": "RB"},
    {"rank": 22, "name": "Trey McBride", "team": "ARI", "position": "TE"},
    {"rank": 23, "name": "Ladd McConkey", "team": "LAC", "position": "WR"},
    {"rank": 24, "name": "Josh Allen", "team": "BUF", "position": "QB"},
    {"rank": 25, "name": "Kyren Williams", "team": "LAR", "position": "RB"},
    {"rank": 26, "name": "Lamar Jackson", "team": "BAL", "position": "QB"},
    {"rank": 27, "name": "Jaxon Smith-Njigba", "team": "SEA", "position": "WR"},
    {"rank": 28, "name": "Chase Brown", "team": "CIN", "position": "RB"},
    {"rank": 29, "name": "Tee Higgins", "team": "CIN", "position": "WR"},
    {"rank": 30, "name": "Jayden Daniels", "team": "WAS", "position": "QB"},
    {"rank": 31, "name": "Tyreek Hill", "team": "MIA", "position": "WR"},
    {"rank": 32, "name": "Breece Hall", "team": "NYJ", "position": "RB"},
    {"rank": 33, "name": "Mike Evans", "team": "TB", "position": "WR"},
    {"rank": 34, "name": "Terry McLaurin", "team": "WAS", "position": "WR"},
    {"rank": 35, "name": "Garrett Wilson", "team": "NYJ", "position": "WR"},
    {"rank": 36, "name": "James Cook", "team": "BUF", "position": "RB"},
    {"rank": 37, "name": "Davante Adams", "team": "LAR", "position": "WR"},
    {"rank": 38, "name": "George Kittle", "team": "SF", "position": "TE"},
    {"rank": 39, "name": "Jalen Hurts", "team": "PHI", "position": "QB"},
    {"rank": 40, "name": "Joe Mixon", "team": "HOU", "position": "RB"},
    {"rank": 41, "name": "DJ Moore", "team": "CHI", "position": "WR"},
    {"rank": 42, "name": "Kenneth Walker III", "team": "SEA", "position": "RB"},
    {"rank": 43, "name": "Rashee Rice", "team": "KC", "position": "WR"},
    {"rank": 44, "name": "Marvin Harrison Jr.", "team": "ARI", "position": "WR"},
    {"rank": 45, "name": "Alvin Kamara", "team": "NO", "position": "RB"},
    {"rank": 46, "name": "Chuba Hubbard", "team": "CAR", "position": "RB"},
    {"rank": 47, "name": "Zay Flowers", "team": "BAL", "position": "WR"},
    {"rank": 48, "name": "Joe Burrow", "team": "CIN", "position": "QB"},
    {"rank": 49, "name": "Courtland Sutton", "team": "DEN", "position": "WR"},
    {"rank": 50, "name": "James Conner", "team": "ARI", "position": "RB"},
    {"rank": 51, "name": "DK Metcalf", "team": "PIT", "position": "WR"},
    {"rank": 52, "name": "DeVonta Smith", "team": "PHI", "position": "WR"},
    {"rank": 53, "name": "Sam LaPorta", "team": "DET", "position": "TE"},
    {"rank": 54, "name": "David Montgomery", "team": "DET", "position": "RB"},
    {"rank": 55, "name": "Omarion Hampton", "team": "LAC", "position": "RB"},
    {"rank": 56, "name": "Jameson Williams", "team": "DET", "position": "WR"},
    {"rank": 57, "name": "Xavier Worthy", "team": "KC", "position": "WR"},
    {"rank": 58, "name": "Aaron Jones Sr.", "team": "MIN", "position": "RB"},
    {"rank": 59, "name": "Baker Mayfield", "team": "TB", "position": "QB"},
    {"rank": 60, "name": "Chris Godwin", "team": "TB", "position": "WR"},
    {"rank": 61, "name": "Chris Olave", "team": "NO", "position": "WR"},
    {"rank": 62, "name": "Patrick Mahomes II", "team": "KC", "position": "QB"},
    {"rank": 63, "name": "TreVeyon Henderson", "team": "NE", "position": "RB"},
    {"rank": 64, "name": "Tony Pollard", "team": "TEN", "position": "RB"},
    {"rank": 65, "name": "Jordan Addison", "team": "MIN", "position": "WR"},
    {"rank": 66, "name": "D'Andre Swift", "team": "CHI", "position": "RB"},
    {"rank": 67, "name": "Jaylen Waddle", "team": "MIA", "position": "WR"},
    {"rank": 68, "name": "T.J. Hockenson", "team": "MIN", "position": "TE"},
    {"rank": 69, "name": "Isiah Pacheco", "team": "KC", "position": "RB"},
    {"rank": 70, "name": "Travis Hunter", "team": "JAC", "position": "WR"},
    {"rank": 71, "name": "George Pickens", "team": "DAL", "position": "WR"},
    {"rank": 72, "name": "Jerry Jeudy", "team": "CLE", "position": "WR"},
    {"rank": 73, "name": "Calvin Ridley", "team": "TEN", "position": "WR"},
    {"rank": 74, "name": "Brian Robinson Jr.", "team": "WAS", "position": "RB"},
    {"rank": 75, "name": "RJ Harvey", "team": "DEN", "position": "RB"},
    {"rank": 76, "name": "Quinshon Judkins", "team": "CLE", "position": "RB"},
    {"rank": 77, "name": "Kaleb Johnson", "team": "PIT", "position": "RB"},
    {"rank": 78, "name": "Kyler Murray", "team": "ARI", "position": "QB"},
    {"rank": 79, "name": "Bo Nix", "team": "DEN", "position": "QB"},
    {"rank": 80, "name": "Mark Andrews", "team": "BAL", "position": "TE"},
    {"rank": 81, "name": "Rome Odunze", "team": "CHI", "position": "WR"},
    {"rank": 82, "name": "Jonnu Smith", "team": "MIA", "position": "TE"},
    {"rank": 83, "name": "Jared Goff", "team": "DET", "position": "QB"},
    {"rank": 84, "name": "Tyrone Tracy Jr.", "team": "NYG", "position": "RB"},
    {"rank": 85, "name": "Tetairoa McMillan", "team": "CAR", "position": "WR"},
    {"rank": 86, "name": "Travis Kelce", "team": "KC", "position": "TE"},
    {"rank": 87, "name": "Jaylen Warren", "team": "PIT", "position": "RB"},
    {"rank": 88, "name": "Najee Harris", "team": "LAC", "position": "RB"},
    {"rank": 89, "name": "Justin Herbert", "team": "LAC", "position": "QB"},
    {"rank": 90, "name": "Evan Engram", "team": "DEN", "position": "TE"},
    {"rank": 91, "name": "Khalil Shakir", "team": "BUF", "position": "WR"},
    {"rank": 92, "name": "Brandon Aiyuk", "team": "SF", "position": "WR"},
    {"rank": 93, "name": "David Njoku", "team": "CLE", "position": "TE"},
    {"rank": 94, "name": "Deebo Samuel Sr.", "team": "WAS", "position": "WR"},
    {"rank": 95, "name": "Caleb Williams", "team": "CHI", "position": "QB"},
    {"rank": 96, "name": "Jayden Reed", "team": "GB", "position": "WR"},
    {"rank": 97, "name": "Jakobi Meyers", "team": "LV", "position": "WR"},
    {"rank": 98, "name": "Jauan Jennings", "team": "SF", "position": "WR"},
    {"rank": 99, "name": "Brock Purdy", "team": "SF", "position": "QB"},
    {"rank": 100, "name": "Jordan Love", "team": "GB", "position": "QB"},
    {"rank": 101, "name": "Rhamondre Stevenson", "team": "NE", "position": "RB"},
    {"rank": 102, "name": "Stefon Diggs", "team": "NE", "position": "WR"},
    {"rank": 103, "name": "Dak Prescott", "team": "DAL", "position": "QB"},
    {"rank": 104, "name": "Tucker Kraft", "team": "GB", "position": "TE"},
    {"rank": 105, "name": "Ricky Pearsall", "team": "SF", "position": "WR"},
    {"rank": 106, "name": "Zach Charbonnet", "team": "SEA", "position": "RB"},
    {"rank": 107, "name": "Cooper Kupp", "team": "SEA", "position": "WR"},
    {"rank": 108, "name": "Josh Downs", "team": "IND", "position": "WR"},
    {"rank": 109, "name": "C.J. Stroud", "team": "HOU", "position": "QB"},
    {"rank": 110, "name": "Drake Maye", "team": "NE", "position": "QB"},
    {"rank": 111, "name": "Travis Etienne Jr.", "team": "JAC", "position": "RB"},
    {"rank": 112, "name": "Michael Pittman Jr.", "team": "IND", "position": "WR"},
    {"rank": 113, "name": "Trevor Lawrence", "team": "JAC", "position": "QB"},
    {"rank": 114, "name": "Javonte Williams", "team": "DAL", "position": "RB"},
    {"rank": 115, "name": "Rachaad White", "team": "TB", "position": "RB"},
    {"rank": 116, "name": "Dalton Kincaid", "team": "BUF", "position": "TE"},
    {"rank": 117, "name": "Justin Fields", "team": "NYJ", "position": "QB"},
    {"rank": 118, "name": "Cam Skattebo", "team": "NYG", "position": "RB"},
    {"rank": 119, "name": "Darnell Mooney", "team": "ATL", "position": "WR"},
    {"rank": 120, "name": "Dallas Goedert", "team": "PHI", "position": "TE"},
    {"rank": 121, "name": "Tank Bigsby", "team": "JAC", "position": "RB"},
    {"rank": 122, "name": "Tyjae Spears", "team": "TEN", "position": "RB"},
    {"rank": 123, "name": "Jordan Mason", "team": "MIN", "position": "RB"},
    {"rank": 124, "name": "Jake Ferguson", "team": "DAL", "position": "TE"},
    {"rank": 125, "name": "Matthew Stafford", "team": "LAR", "position": "QB"},
    {"rank": 126, "name": "Tua Tagovailoa", "team": "MIA", "position": "QB"},
    {"rank": 127, "name": "Christian Kirk", "team": "HOU", "position": "WR"},
    {"rank": 128, "name": "Keon Coleman", "team": "BUF", "position": "WR"},
    {"rank": 129, "name": "Tyler Warren", "team": "IND", "position": "TE"},
    {"rank": 130, "name": "Rico Dowdle", "team": "CAR", "position": "RB"},
    {"rank": 131, "name": "Rashid Shaheed", "team": "NO", "position": "WR"},
    {"rank": 132, "name": "Luther Burden III", "team": "CHI", "position": "WR"},
    {"rank": 133, "name": "Bhayshul Tuten", "team": "JAC", "position": "RB"},
    {"rank": 134, "name": "Kyle Pitts", "team": "ATL", "position": "TE"},
    {"rank": 135, "name": "Bryce Young", "team": "CAR", "position": "QB"},
    {"rank": 136, "name": "Ray Davis", "team": "BUF", "position": "RB"},
    {"rank": 137, "name": "Trey Benson", "team": "ARI", "position": "RB"},
    {"rank": 138, "name": "Austin Ekeler", "team": "WAS", "position": "RB"},
    {"rank": 139, "name": "Pat Freiermuth", "team": "PIT", "position": "TE"},
    {"rank": 140, "name": "Emeka Egbuka", "team": "TB", "position": "WR"},
    {"rank": 141, "name": "J.J. McCarthy", "team": "MIN", "position": "QB"},
    {"rank": 142, "name": "Hunter Henry", "team": "NE", "position": "TE"},
    {"rank": 143, "name": "Isaac Guerendo", "team": "SF", "position": "RB"},
    {"rank": 144, "name": "Tyler Allgeier", "team": "ATL", "position": "RB"},
    {"rank": 145, "name": "Rashod Bateman", "team": "BAL", "position": "WR"},
    {"rank": 146, "name": "Jalen McMillan", "team": "TB", "position": "WR"},
    {"rank": 147, "name": "Michael Penix Jr.", "team": "ATL", "position": "QB"},
    {"rank": 148, "name": "Colston Loveland", "team": "CHI", "position": "TE"},
    {"rank": 149, "name": "Jaylen Wright", "team": "MIA", "position": "RB"},
    {"rank": 150, "name": "Zach Ertz", "team": "WAS", "position": "TE"},
    {"rank": 151, "name": "Romeo Doubs", "team": "GB", "position": "WR"},
    {"rank": 152, "name": "Quentin Johnston", "team": "LAC", "position": "WR"},
    {"rank": 153, "name": "Marvin Mims Jr.", "team": "DEN", "position": "WR"},
    {"rank": 154, "name": "Marquise Brown", "team": "KC", "position": "WR"},
    {"rank": 155, "name": "Blake Corum", "team": "LAR", "position": "RB"},
    {"rank": 156, "name": "Adam Thielen", "team": "CAR", "position": "WR"},
    {"rank": 157, "name": "Geno Smith", "team": "LV", "position": "QB"},
    {"rank": 158, "name": "Cedric Tillman", "team": "CLE", "position": "WR"},
    {"rank": 159, "name": "Jaydon Blue", "team": "DAL", "position": "RB"},
    {"rank": 160, "name": "Jerome Ford", "team": "CLE", "position": "RB"},
    {"rank": 161, "name": "Braelon Allen", "team": "NYJ", "position": "RB"},
    {"rank": 162, "name": "Sam Darnold", "team": "SEA", "position": "QB"},
    {"rank": 163, "name": "Isaiah Likely", "team": "BAL", "position": "TE"},
    {"rank": 164, "name": "Kyle Williams", "team": "NE", "position": "WR"},
    {"rank": 165, "name": "DeAndre Hopkins", "team": "BAL", "position": "WR"},
    {"rank": 166, "name": "Roschon Johnson", "team": "CHI", "position": "RB"},
    {"rank": 167, "name": "Audric Estime", "team": "DEN", "position": "RB"},
    {"rank": 168, "name": "MarShawn Lloyd", "team": "GB", "position": "RB"},
    {"rank": 169, "name": "Cameron Ward", "team": "TEN", "position": "QB"},
    {"rank": 170, "name": "Cade Otton", "team": "TB", "position": "TE"},
    {"rank": 171, "name": "Mike Gesicki", "team": "CIN", "position": "TE"},
    {"rank": 172, "name": "Denver Broncos", "team": "DEN", "position": "DST"},
    {"rank": 173, "name": "Xavier Legette", "team": "CAR", "position": "WR"},
    {"rank": 174, "name": "Philadelphia Eagles", "team": "PHI", "position": "DST"},
    {"rank": 175, "name": "Matthew Golden", "team": "GB", "position": "WR"},
    {"rank": 176, "name": "Alec Pierce", "team": "IND", "position": "WR"},
    {"rank": 177, "name": "Tre Harris", "team": "LAC", "position": "WR"},
    {"rank": 178, "name": "Jaleel McLaughlin", "team": "DEN", "position": "RB"},
    {"rank": 179, "name": "Minnesota Vikings", "team": "MIN", "position": "DST"},
    {"rank": 180, "name": "Pittsburgh Steelers", "team": "PIT", "position": "DST"},
    {"rank": 181, "name": "Jalen Coker", "team": "CAR", "position": "WR"},
    {"rank": 182, "name": "Keenan Allen", "team": "FA", "position": "WR"},
    {"rank": 183, "name": "Anthony Richardson Sr.", "team": "IND", "position": "QB"},
    {"rank": 184, "name": "Baltimore Ravens", "team": "BAL", "position": "DST"},
    {"rank": 185, "name": "Devin Neal", "team": "NO", "position": "RB"},
    {"rank": 186, "name": "Wan'Dale Robinson", "team": "NYG", "position": "WR"},
    {"rank": 187, "name": "Dalton Schultz", "team": "HOU", "position": "TE"},
    {"rank": 188, "name": "Dontayvion Wicks", "team": "GB", "position": "WR"},
    {"rank": 189, "name": "DeMario Douglas", "team": "NE", "position": "WR"},
    {"rank": 190, "name": "Kansas City Chiefs", "team": "KC", "position": "DST"},
    {"rank": 191, "name": "Joshua Palmer", "team": "BUF", "position": "WR"},
    {"rank": 192, "name": "Mason Taylor", "team": "NYJ", "position": "TE"},
    {"rank": 193, "name": "Jake Bates", "team": "DET", "position": "K"},
    {"rank": 194, "name": "Cole Kmet", "team": "CHI", "position": "TE"},
    {"rank": 195, "name": "Detroit Lions", "team": "DET", "position": "DST"},
    {"rank": 196, "name": "J.K. Dobbins", "team": "FA", "position": "RB"},
    {"rank": 197, "name": "Kendre Miller", "team": "NO", "position": "RB"},
    {"rank": 198, "name": "Brandon Aubrey", "team": "DAL", "position": "K"},
    {"rank": 199, "name": "Houston Texans", "team": "HOU", "position": "DST"},
    {"rank": 200, "name": "Chig Okonkwo", "team": "TEN", "position": "TE"},
    {"rank": 201, "name": "Buffalo Bills", "team": "BUF", "position": "DST"},
    {"rank": 202, "name": "DJ Giddens", "team": "IND", "position": "RB"},
    {"rank": 203, "name": "Los Angeles Chargers", "team": "LAC", "position": "DST"},
    {"rank": 204, "name": "Wil Lutz", "team": "DEN", "position": "K"},
    {"rank": 205, "name": "Michael Wilson", "team": "ARI", "position": "WR"},
    {"rank": 206, "name": "Cameron Dicker", "team": "LAC", "position": "K"},
    {"rank": 207, "name": "Chris Boswell", "team": "PIT", "position": "K"},
    {"rank": 208, "name": "Adonai Mitchell", "team": "IND", "position": "WR"},
    {"rank": 209, "name": "New York Jets", "team": "NYJ", "position": "DST"},
    {"rank": 210, "name": "Jack Bech", "team": "LV", "position": "WR"},
    {"rank": 211, "name": "Ja'Tavion Sanders", "team": "CAR", "position": "TE"},
    {"rank": 212, "name": "Justice Hill", "team": "BAL", "position": "RB"},
    {"rank": 213, "name": "Seattle Seahawks", "team": "SEA", "position": "DST"},
    {"rank": 214, "name": "Green Bay Packers", "team": "GB", "position": "DST"},
    {"rank": 215, "name": "Ka'imi Fairbairn", "team": "HOU", "position": "K"},
    {"rank": 216, "name": "Kareem Hunt", "team": "KC", "position": "RB"},
    {"rank": 217, "name": "Chase McLaughlin", "team": "TB", "position": "K"},
    {"rank": 218, "name": "Evan McPherson", "team": "CIN", "position": "K"},
    {"rank": 219, "name": "Andrei Iosivas", "team": "CIN", "position": "WR"},
    {"rank": 220, "name": "Elijah Arroyo", "team": "SEA", "position": "TE"},
    {"rank": 221, "name": "Jayden Higgins", "team": "HOU", "position": "WR"},
    {"rank": 222, "name": "Los Angeles Rams", "team": "LAR", "position": "DST"},
    {"rank": 223, "name": "Brenton Strange", "team": "JAC", "position": "TE"},
    {"rank": 224, "name": "Amari Cooper", "team": "FA", "position": "WR"},
    {"rank": 225, "name": "Harrison Butker", "team": "KC", "position": "K"},
    {"rank": 226, "name": "Russell Wilson", "team": "NYG", "position": "QB"},
    {"rank": 227, "name": "Darius Slayton", "team": "NYG", "position": "WR"},
    {"rank": 228, "name": "Younghoe Koo", "team": "ATL", "position": "K"},
    {"rank": 229, "name": "Ollie Gordon II", "team": "MIA", "position": "RB"},
    {"rank": 230, "name": "Kenneth Gainwell", "team": "PIT", "position": "RB"},
    {"rank": 231, "name": "Dylan Sampson", "team": "CLE", "position": "RB"},
    {"rank": 232, "name": "Nick Chubb", "team": "FA", "position": "RB"},
    {"rank": 233, "name": "Tyler Bass", "team": "BUF", "position": "K"},
    {"rank": 234, "name": "San Francisco 49ers", "team": "SF", "position": "DST"},
    {"rank": 235, "name": "Tampa Bay Buccaneers", "team": "TB", "position": "DST"},
    {"rank": 236, "name": "Jake Elliott", "team": "PHI", "position": "K"},
    {"rank": 237, "name": "Elijah Mitchell", "team": "KC", "position": "RB"},
    {"rank": 238, "name": "Jason Sanders", "team": "MIA", "position": "K"},
    {"rank": 239, "name": "Elic Ayomanor", "team": "TEN", "position": "WR"},
    {"rank": 240, "name": "Juwan Johnson", "team": "NO", "position": "TE"},
    {"rank": 241, "name": "Antonio Gibson", "team": "NE", "position": "RB"},
    {"rank": 242, "name": "Miles Sanders", "team": "DAL", "position": "RB"},
    {"rank": 243, "name": "Keaton Mitchell", "team": "BAL", "position": "RB"},
    {"rank": 244, "name": "Jaylin Noel", "team": "HOU", "position": "WR"},
    {"rank": 245, "name": "Khalil Herbert", "team": "IND", "position": "RB"},
    {"rank": 246, "name": "Devin Singletary", "team": "NYG", "position": "RB"},
    {"rank": 247, "name": "Devaughn Vele", "team": "DEN", "position": "WR"},
    {"rank": 248, "name": "Jalen Tolbert", "team": "DAL", "position": "WR"},
    {"rank": 249, "name": "Kyle Monangai", "team": "CHI", "position": "RB"},
    {"rank": 250, "name": "Cleveland Browns", "team": "CLE", "position": "DST"},
    {"rank": 251, "name": "Brandin Cooks", "team": "NO", "position": "WR"},
    {"rank": 252, "name": "Dallas Cowboys", "team": "DAL", "position": "DST"},
    {"rank": 253, "name": "Diontae Johnson", "team": "CLE", "position": "WR"},
    {"rank": 254, "name": "Kayshon Boutte", "team": "NE", "position": "WR"},
    {"rank": 255, "name": "Calvin Austin III", "team": "PIT", "position": "WR"},
    {"rank": 256, "name": "Raheem Mostert", "team": "LV", "position": "RB"},
    {"rank": 257, "name": "Aaron Rodgers", "team": "PIT", "position": "QB"},
    {"rank": 258, "name": "Will Shipley", "team": "PHI", "position": "RB"},
    {"rank": 259, "name": "Tyler Lockett", "team": "TEN", "position": "WR"},
    {"rank": 260, "name": "Trevor Etienne", "team": "CAR", "position": "RB"},
    {"rank": 261, "name": "Nick Westbrook-Ikhine", "team": "MIA", "position": "WR"},
    {"rank": 262, "name": "Jalen Royals", "team": "KC", "position": "WR"},
    {"rank": 263, "name": "Sincere McCormick", "team": "LV", "position": "RB"},
    {"rank": 264, "name": "Malik Washington", "team": "MIA", "position": "WR"},
    {"rank": 265, "name": "Taysom Hill", "team": "NO", "position": "TE"},
    {"rank": 266, "name": "Noah Fant", "team": "SEA", "position": "TE"},
    {"rank": 267, "name": "Roman Wilson", "team": "PIT", "position": "WR"},
    {"rank": 268, "name": "Elijah Moore", "team": "BUF", "position": "WR"},
    {"rank": 269, "name": "Tahj Brooks", "team": "CIN", "position": "RB"},
    {"rank": 270, "name": "Zack Moss", "team": "CIN", "position": "RB"},
    {"rank": 271, "name": "Sean Tucker", "team": "TB", "position": "RB"},
    {"rank": 272, "name": "Ty Johnson", "team": "BUF", "position": "RB"},
    {"rank": 273, "name": "Kimani Vidal", "team": "LAC", "position": "RB"},
    {"rank": 274, "name": "Mike Williams", "team": "LAC", "position": "WR"},
    {"rank": 275, "name": "Harold Fannin Jr.", "team": "CLE", "position": "TE"},
    {"rank": 276, "name": "Joshua Karty", "team": "LAR", "position": "K"},
    {"rank": 277, "name": "Noah Gray", "team": "KC", "position": "TE"},
    {"rank": 278, "name": "Gabe Davis", "team": "FA", "position": "WR"},
    {"rank": 279, "name": "Alexander Mattison", "team": "MIA", "position": "RB"},
    {"rank": 280, "name": "Tim Patrick", "team": "DET", "position": "WR"},
    {"rank": 281, "name": "Dameon Pierce", "team": "HOU", "position": "RB"},
    {"rank": 282, "name": "Isaiah Davis", "team": "NYJ", "position": "RB"},
    {"rank": 283, "name": "Tre Tucker", "team": "LV", "position": "WR"},
    {"rank": 284, "name": "Matt Gay", "team": "WAS", "position": "K"},
    {"rank": 285, "name": "Chicago Bears", "team": "CHI", "position": "DST"},
    {"rank": 286, "name": "Ty Chandler", "team": "MIN", "position": "RB"},
    {"rank": 287, "name": "Pat Bryant", "team": "DEN", "position": "WR"},
    {"rank": 288, "name": "Xavier Restrepo", "team": "TEN", "position": "WR"},
    {"rank": 289, "name": "Parker Washington", "team": "JAC", "position": "WR"},
    {"rank": 290, "name": "Chris Brooks", "team": "GB", "position": "RB"},
    {"rank": 291, "name": "Dyami Brown", "team": "JAC", "position": "WR"},
    {"rank": 292, "name": "Brashard Smith", "team": "KC", "position": "RB"},
    {"rank": 293, "name": "Miami Dolphins", "team": "MIA", "position": "DST"},
    {"rank": 294, "name": "Jason Myers", "team": "SEA", "position": "K"},
    {"rank": 295, "name": "Woody Marks", "team": "HOU", "position": "RB"},
    {"rank": 296, "name": "Luke McCaffrey", "team": "WAS", "position": "WR"},
    {"rank": 297, "name": "Jalen Nailor", "team": "MIN", "position": "WR"},
    {"rank": 298, "name": "Will Dissly", "team": "LAC", "position": "TE"},
    {"rank": 299, "name": "Jordan James", "team": "SF", "position": "RB"},
    {"rank": 300, "name": "Player 300", "team": "TEAM", "position": "POS"},
]